In [1]:
import numpy as np

In [2]:
#Write a NumPy program to replace the negative values in a NumPy array with 0.
a = np.array([1, 2, 3, 4, -5, -6, 7])
a[a<0] = 0
print(a)

[1 2 3 4 0 0 7]


In [3]:
#Q5- Write a NumPy program to create an array of (3, 4) shapes, multiply every element value by 3 and display the result array.
a = np.arange(12).reshape(3,4)
print("array elements:", a)
a*=3
print("new array elements:", a)

array elements: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
new array elements: [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
