In [2]:
import numpy as np

In [2]:
#Write a NumPy program to replace the negative values in a NumPy array with 0.
a = np.array([1, 2, 3, 4, -5, -6, 7])
a[a<0] = 0
print(a)

[1 2 3 4 0 0 7]


In [3]:
#Q5- Write a NumPy program to create an array of (3, 4) shapes, multiply every element value by 3 and display the result array.
a = np.arange(12).reshape(3,4)
print("array elements:", a)
a*=3
print("new array elements:", a)

array elements: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
new array elements: [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [3]:
#Program to check numpy version
print(np.__version__)

1.23.5


In [4]:
#Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.
Original_List = [12.23, 13.32, 100, 36.32]
OneDimensional_List = np.array(Original_List)
print("Original List: ", Original_List,"\nOne-dimensional Numpy array: ", OneDimensional_List)

Original List:  [12.23, 13.32, 100, 36.32] 
One-dimensional Numpy array:  [ 12.23  13.32 100.    36.32]


In [5]:
#Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
matrix_list = [[2,3,4],[5,6,7],[8,9,10]]
matrix = np.array(matrix_list)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [6]:
#Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.
arr = np.zeros(10)
print(arr)
arr[6] = 11
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [7]:
#Write a NumPy program to create an array with values ranging from 12 to 38.
arr = np.arange(12, 38)
print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [8]:
#Write a NumPy program to reverse an array (the first element becomes the last).
arr = np.arange(12, 38)
print(arr)
print("Reverse: ", arr[::-1])

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse:  [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [9]:
#Write a NumPy program to convert an array to a floating type.
int_arr = np.array([1, 2, 3, 4, 5])
float_arr = int_arr.astype(float)
print(float_arr)

[1. 2. 3. 4. 5.]


In [10]:
#Write a NumPy program to create a 2D array with 1 on the border and 0 inside.
x = np.ones((5, 5))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
#Write a NumPy program to add a border (filled with 0's) around an existing array.
x = np.zeros((5, 5))
x[1:-1, 1:-1] = 1
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
